# Generated by Django 4.0.4 on 2022-12-20 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_product_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='noyes',
            new_name='availability',
        ),
    ]
