# Generated by Django 4.0.4 on 2023-01-23 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_customer_user_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tag',
            field=models.BooleanField(choices=[(True, 'Women'), (False, 'Men')], default=True, null=None),
        ),
    ]
