# Generated by Django 4.0.4 on 2023-06-06 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_product_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='user',
            new_name='userr',
        ),
    ]
