# Generated by Django 4.0.4 on 2023-06-21 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_carousel'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousel',
            name='slide_number',
            field=models.IntegerField(null=True),
        ),
    ]
