# Generated by Django 4.0.4 on 2023-06-21 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_carousel_slide_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sale',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sale', to='app.carousel'),
        ),
    ]
