# Generated by Django 4.0.4 on 2023-06-21 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_product_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='saleprice',
            field=models.IntegerField(null=True),
        ),
    ]
