# Generated by Django 4.0.4 on 2023-06-21 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='size',
            field=models.CharField(choices=[('1', 'XXS'), ('2', 'XS'), ('3', 'S'), ('4', 'M'), ('5', 'L'), ('6', 'XL'), ('7', 'XXL'), ('8', 'XXXL')], default='1', max_length=20, null=True),
        ),
    ]
