# Generated by Django 4.2.2 on 2023-06-22 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_brand_product_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='saleprice',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
